WS_URL=ws://192.168.1.228:8084/edge/wss/73965d62-de33-4299-8021-4a22505486b9
SERVER_IP=192.168.1.228
SERVER_PORT=7058
DB_URL=jdbc:postgresql://192.168.1.228:5432/postgres
DB_USERNAME=postgres
DB_PASSWORD=Bitcomm@123
WEBSOCKET_WAIT_TIME=5000
DATABASE_WAIT_TIME=2000
TEST_JSON_PATH= src\\main\\java\\backend\\test\\testjson.data
MESSAGE_JSON_PATH=src\\main\\java\\backend\\test\\messageJson.data