<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cn.org.thinkcloud</groupId>
    <artifactId>think-cloud-build</artifactId>
    <version>2.0.0.RELEASE</version>
  </parent>
  <groupId>MobileTesting</groupId>
  <artifactId>MobileTesting</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <properties>
    <rversion>2.0.0.RELEASE</rversion>
  </properties>
  <!--OWN Dependencies -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>MobileTesting-domain</artifactId>
        <version>0.0.1-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>MobileTesting-repo-api</artifactId>
        <version>0.0.1-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>MobileTesting-biz-api</artifactId>
        <version>0.0.1-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>MobileTesting-manager-api</artifactId>
        <version>0.0.1-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>MobileTesting-commons</artifactId>
        <version>0.0.1-SNAPSHOT</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <modules>
    <module>MobileTesting-domain</module>
    <module>MobileTesting-commons</module>
    <module>MobileTesting-repo-api</module>
    <module>MobileTesting-biz-api</module>
    <module>MobileTesting-manager-api</module>
    <module>MobileTesting-biz-provider</module>
    <module>MobileTesting-repo-provider</module>
    <module>MobileTesting-manager-provider</module>
    <module>MobileTesting-ctl</module>
  </modules>
</project>
