## ---------------------------------------------------------
## Framework configuration
## ---------------------------------------------------------
base.url=https://jmdservice.com/
training.url=https://jmdservice.com/traning-skill-development/
blog.url=https://jmdservice.com/category/blog/
about.url=https://jmdservice.com/about-us/
contact.url=https://jmdservice.com/contact-us/

# chrome | firefox | edge
browser=chrome

# run browser without a visible UI window (true/false)
headless=false

implicit.wait.seconds=5
explicit.wait.seconds=15
page.load.timeout.seconds=30

screenshot.dir=test-output/screenshots
